apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: content-validator
  namespace: knative-demo
  labels:
    app: content-validator
    demo: knative-learning
spec:
  template:
    metadata:
      labels:
        app: content-validator
      annotations:
        autoscaling.knative.dev/min-scale: "0"
        autoscaling.knative.dev/max-scale: "10"
    spec:
      containers:
      - image: docker.io/rudder9290/content-validator:latest
        name: app
        ports:
        - containerPort: 8080
          name: http1
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: content-validator-trigger
  namespace: knative-demo
  labels:
    app: content-validator
spec:
  broker: learning-broker
  filter:
    attributes:
      type: com.learning.message.extracted
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: content-validator
